.TH RACTL 8 "June 2014" "ratools"
.SH NAME
ractl \- Router Advertisement Control (ratools/ractl)
.SH SYNOPSIS
.B ractl
[\fB\-s|--socket\fR \fIUNIXSOCKET\fR]
.IR command ...
.SH DESCRIPTION
Control program for the Router Advertisement Daemin (ratools/rad) providing an
easy to use command line interface.
.SH OPTIONS
.TP 8
.BR --socket
Override default path of the control socket.
.SH BUILT-IN COMMANDS
.TP 8
.BR dump
Print configuration of all Router Advertisements to stdout.
.TP 8
.BR show
Show all Router Advertisements.
.TP 8
.BR version
Show version information for ratools/ractl.
.TP 8
.BR loglevel
Set logging level of rad. Possible values are 'info', 'warning', and
'error'.
.SH MODULE COMMANDS
There are more commands provided by modules. To learn more about them, have a
look at the module's manual pages.
.SH AVAILABILITY
.B ractl
is part of the ratools framework available from https://github.com/danrl/ratools
.SH AUTHOR
Written by Dan Luedtke.
