.TH RACTL 1
.SH NAME
ractl \- a client to manipulate the configuration of rad
.SH DESCRIPTION
The basic idea is to have two programs. On the one hand a powerful CLI, called ratools/ractl, for manipulating the configuration. And on the other hand an efficient, non-bloated stable daemon process, called ratools/rad. Both programs communicate with each other via an UNIX socket.
.SH OPTIONS
.TP
.BR dump
Dumps the configuration of the created ICMPv6 packet.
.TP
.BR show
Shows the created ICMPv6 packet.
.TP
.BR  version
Shows the version of ractl.
.SH AUTHOR
Written by Dan Luedtke.
