.TH RACTL 1
.SH NAME
ractl \- a client to manipulate the configuration of rad
.SH DESCRIPTION
The basic idea is to have two programs. On the one hand a powerful CLI, called ratools/ractl, for manipulating the configuration. And on the other hand an efficient, non-bloated stable daemon process, called ratools/rad. Both programs communicate with each other via an UNIX socket.
.SH OPTIONS
.TP
.BR dump
Print configuration of all Router Advertisements to stdout.
.TP
.BR show
Show all Router Advertisements.
.TP
.BR version
Show version information for ratools/ractl.
.TP
.BR loglevel
Set log level of ratools/rad. Possible values are 'info', 'warning', and 'error'.
.SH AUTHOR
Written by Dan Luedtke.
