.TH RAD 8 "June 2014" "ratools"
.SH NAME
rad \- Router Advertisement Daemon (ratools/rad)
.SH SYNOPSIS
.B rad
[\fB\-s|--socket\fR \fIUNIXSOCKET\fR]
[\fB\-l|--loglevel\fR \fILOGGING LEVEL\fR]
.IR command ...
.SH DESCRIPTION
ratools/rad is a fast, dynamic, multi-threading daemon for sending IPv6 Router Advertisements (RA).
.SH OPTIONS
.TP
.BR --socket
Override default path of the control socket.
.TP
.BR --loglevel
Set log level of ratools/rad. Possible values are 'info', 'warning', and 'error'.
.SH AUTHOR
Written by Dan Luedtke.
